### ISSUE TITLE
Add/configure 404 page route for non-existing routes

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/collabo-community-app#44]
#### Issue
We don't have a 404 route/page for when a route/page does not exist in our web app: https://github.com/code-collabo/collabo-community-app

#### Expected solution
- Add/configure a 404 page route for when a route does not exist, so that when we type or paste a non-existing page route url in the browser, the user is redirected to the 404 page route.
- Note: We do not need you to add the figma design. Just use the basic things we have there in the app code for now.

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] 404 page route has been added/configured for when a route does not exist
- [ ] User is redirected to the 404 page route, if they type or paste a non-existing page route url in the browser
- [ ] Figma design is not added. Only the basic things we have there in the app code are used in this submisson.
- [ ] I certify that I ran my checklist

**Comment by tylerjusfly** [comment]
Will i be the one to check or mark the checklist when i make a pull request? or i just add it and the reviewer will check it when he/she has tested it.

**Comment by Ifycode** [comment]
Our engineers are also QA engineers 🤓😂 We like software engineers to be vigilant and mindful of what they help fix/solve.
So yes, after you are through, please check the checkboxes. Thank you @tylerjusfly 
Are you taking this on, so I can assign you?

**Comment by tylerjusfly** [comment]
yes please Assign this to me.

**Comment by Ifycode** [comment]
Assigned to you @tylerjusfly 👍🏼🎉
