### ISSUE TITLE
Add (Code Collabo) favicon to community app

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/collabo-community-app#45]
#### Issue and expected result
The favicon (i.e. the tiny image beside the page title in the browser tab) that is currently in the app is not our own.
- Reach out to Collabo Community designer @Geefundesign (Isaiah) to know what to use as favicon (please use the appropriate public channel on our discord server for this discussion, not DM).
- Help us change/add the favicon for `Code Collabo` to the app: https://github.com/code-collabo/collabo-community-app

**Comment by Akpjunior94** [comment]
@Ifycode please assign this to me

**Comment by Ifycode** [comment]
Nice pick @Akpjunior94 Assigned to you 💯
