### ISSUE TITLE
[Mobile App] Mobile (iOS & Android) screens or features to create figma designs for

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/collabo-community-app#51]
#### First timer onboarding screens for the mobile app
- [x] **_First timer swipe screens:_** examples - https://www.pinterest.com/pin/travel-startup-app-onboarding--399342691968715982/
    - **_First swipe screen:_** Image + text which says "**_Upgrade from dummy projects:_** Find interesting job-worthy open source projects to contribute to within Collabo Community based on your area of interest"
    - **_Second swipe screen:_** Image + text which says "**_Collabo Updates:_** Get notified when new careers opportunities or projects are available to collaborate on within Collabo Community"
    - **_Third swipe screen:_** Image + text which says "**_Collabo Onboarding:_** Get step by step guidance on what you need to do before you start contributing and collaborating through the Collabo community's app onboarding feature"
    -  **_Fourth swipe screen:_** Image + text which says "**_Have fun collaborating:_** Join many more contributors in the Collabo community to have fun while learning as we build awesome projects"

- [x] `Go to Community App` button - should this be on the 4th first timer swipe screen? I think so.

- [x] User should be able to **_skip_** first timer screens and just go straight to community app if they don't which to go through those screens.

#### The mobile app proper
- [x] **_Sidebar buttons or links (when not logged in):_**
    - Onboarding
    - Projects
    - Careers
    - Donate
> How do we implement **_login_** and **_signup_**? - should these also be buttons on the sidebar? Or should they get a separate page?

- [x] **_Sidebar buttons or links (when logged in):_**
    - Onboarding
    - Projects
    - Careers
    - Donate
    - Settings **_(settings should only be visible/available when community contributor has logged in)_**
> How do we implement **_logout_**? - should these also be buttons on the sidebar?

- [x] **_Onboarding page screen (for when user is not logged in)_**
        - Let user know that the onboarding is only available to community members or users who are logged in
        - ~Note: We need the top left hamburger menu here~

- [x] **_Project page/screen filters:_** Mobile (iOS/Android) version of filters for the projects page/screens

**Comment by Blessed-Samuel** [comment]
Hello.
I'd like to join on this project

**Comment by Ifycode** [comment]
Please see my comment here: https://github.com/code-collabo/collabo-community-app/issues/41?notification_referrer_id=NT_kwDOArF5bLM4MTA3Mzc2MDc0OjQ1MTg1Mzg4#issuecomment-1801880754
@Blessed-Samuel If you need more clarification about my response, please ask in the community channel so that you can get better guidance.

**Comment by Blessed-Samuel** [comment]
Alright Mam
