### ISSUE TITLE
[Web App] Configure linting with ESlint rules to work like that of the backend

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/collabo-community-app#56]
#### Description
Nextjs set up eslint and config when we created the [community app's web client](https://github.com/code-collabo/collabo-community-app), but there are still no rules in there to help keep developer's code uniform.

#

#### Expected solution
We want the same linting configuration like the **_ts_** and **_esm_** templates in the [api-boilerplate-templates](https://github.com/code-collabo/node-mongo-api-boilerplate-templates).That said here is what we want to achieve: 
- Eslint should throw warnings and errors (in form of wiggly lines) in code editor's interface when necessary while writing ts or js code
- Watch Eslint in the terminal anytime the web client server starts or reloads for the ts or js script files. The errors and warnings should show up in the terminal accordingly.

#

#### Additional context
- You may want to first test/checkout, run and make changes to the node-mongo api boilerplates, to get a better idea of how eslint works in there as described above.
- Note, the goal is not to use a tool like prettier to do the work of formatting. Do not add prettier or any tool that works like it. We just want code developers to be conscious and be mindful of the uniformity in code writing styles.

#

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] I have tested that this eslint solution works and behaves like that of the [api-boilerplate-templates](https://github.com/code-collabo/node-mongo-api-boilerplate-templates).
- [ ] Eslint throws warnings and errors (in form of wiggly lines) in code editor's interface when necessary while writing ts or js code
- [ ] Eslint is being watched in the terminal anytime the web client server starts or reloads for the ts or js script files. The errors and warnings show up in the terminal accordingly.
- [ ] I certify that I ran my checklist

**Comment by Akpjunior94** [comment]
@Ifycode I will like to take on this

**Comment by Ifycode** [comment]
Assigned to you @Akpjunior94
