### ISSUE TITLE
[Web App] Fix multiple routes for the 1st page of each app in our 3-in-1 app

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/collabo-community-app#60]
> Note: Pull new changes in develop branch first

#### Issue description
We have multiple routes leading to just one page i.e. the 1st page of each app in our 3-in-1 app.

#

#### Steps to reproduce the issue
1. Go to https://github.com/code-collabo/collabo-community-app, and run the app locally
2. For community/home: Check these 3 routes to see that its just the home page of the app they all point to: `http://localhost:3000`, `http://localhost:3000/community` and `http://localhost:3000/community/home` 
3. For code-collabo overview: Check these 2 routes to see that its just the overview page of the code-collabo app they all point to: `http://localhost:3000/code-collabo` and `http://localhost:3000/code-collabo/overview` 
4. For other-subcommunity overview: Check these 2 routes to see that its just the overview page of the code-collabo app they all point to: `http://localhost:3000/other-subcommunity` and `http://localhost:3000/other-subcommunity/overview` 

#

#### Expected behavior
- community/home urls should be redirected to `http://localhost:3000`
- code-collabo overview urls should be redirected to `http://localhost:3000/code-collabo`
- other-subcommunity overview urls should be redirected to `http://localhost:3000/other-subcommunity`

#

#### Additional context
We don't want to change the structure of the `pages` or `app` folder content while doing this. Work with existing structure.

#

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] The structure of the `pages` or `app` folder are intact as they were before
- [ ] community/home urls are redirected to `http://localhost:3000`
- [ ] code-collabo overview urls are redirected to `http://localhost:3000/code-collabo`
- [ ] other-subcommunity overview urls are redirected to `http://localhost:3000/other-subcommunity`
- [ ] I certify that I ran my checklist

**Comment by Akpjunior94** [comment]
Hey @Ifycode can I work on this issue?

**Comment by Ifycode** [comment]
Not yet @Akpjunior94 
You are still working on some other issue.

See the **_Finding issue tickets and assignments to work on_** section of our new community contributing guide: https://docs.collabocommunity.com/contribute/#finding-issue-tickets-and-assignments-to-work-on

If someone else has not been assigned to this issue before you come back again, you can then request to be assigned to it.
