### ISSUE TITLE
[Web App] Make EsLint scream for indent and trailing white spaces

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/collabo-community-app#69]
> Note: Pull new changes in develop branch first

#### Description
We've been able to make eslint scream at some inconsistencies in the [community app's web client](https://github.com/code-collabo/collabo-community-app), but there are still some more we'll like to address:
- **Spacing before i.e. on the left side of lines of code:** We have a mix of indent or tab size of 2 and 4. If it's not 2, EsLint should scream (both on )
- **Trailing white spaces:** on the right of any line of code, any space there after e.g. the semicolon that ends the code should make eslint scream.

#

#### Expected solution
- Indent spacing should be 2
- No trailing spaces at the end (i.e right side) of any line of code

#

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] Eslint screams when indent is not 2
- [ ] Eslint screams when trailing white space is left at the end (right side) of a line of code.
- [ ] I've checked that Eslint screams the above both (in form of wiggly lines) in code editor's interface, and in the terminal when you run any of the lint commands
- [ ] I've checked that Eslint screams both in js and ts files
- [ ] I certify that I ran my checklist

**Comment by Dkingofcode** [comment]
Can i work on this issue?

**Comment by Ifycode** [comment]
Assigned to you @Dkingofcode
